# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='world.proto',
  package='relay',
  syntax='proto3',
  serialized_pb=_b('\n\x0bworld.proto\x12\x05relay\"\'\n\x05World\x12\x1e\n\x04\x64irs\x18\x01 \x03(\x0e\x32\x10.relay.Direction\"(\n\x08WorldSet\x12\x1c\n\x06worlds\x18\x01 \x03(\x0b\x32\x0c.relay.World*2\n\tDirection\x12\t\n\x05RIGHT\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\x06\n\x02UP\x10\x02\x12\x08\n\x04\x44OWN\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='relay.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=105,
  serialized_end=155,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
RIGHT = 0
LEFT = 1
UP = 2
DOWN = 3



_WORLD = _descriptor.Descriptor(
  name='World',
  full_name='relay.World',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dirs', full_name='relay.World.dirs', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_WORLDSET = _descriptor.Descriptor(
  name='WorldSet',
  full_name='relay.WorldSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worlds', full_name='relay.WorldSet.worlds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=103,
)

_WORLD.fields_by_name['dirs'].enum_type = _DIRECTION
_WORLDSET.fields_by_name['worlds'].message_type = _WORLD
DESCRIPTOR.message_types_by_name['World'] = _WORLD
DESCRIPTOR.message_types_by_name['WorldSet'] = _WORLDSET
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION

World = _reflection.GeneratedProtocolMessageType('World', (_message.Message,), dict(
  DESCRIPTOR = _WORLD,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:relay.World)
  ))
_sym_db.RegisterMessage(World)

WorldSet = _reflection.GeneratedProtocolMessageType('WorldSet', (_message.Message,), dict(
  DESCRIPTOR = _WORLDSET,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:relay.WorldSet)
  ))
_sym_db.RegisterMessage(WorldSet)


# @@protoc_insertion_point(module_scope)
